- name: Updates apt cache
  apt: update_cache=true
  sudo: yes

- name: Installs git and goloang
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - golang
  sudo: yes

- name: check whether already installed
  stat: path={{ etcd_install_prefix }}/etcd/installed.ok
  register: etcd_installed

- name: checkout code
  git: repo=https://github.com/coreos/etcd.git
       dest={{ etcd_install_prefix }}/etcd
       version=v0.4.1
  sudo: yes
  when: etcd_installed.stat.exists != true

- name: build etcd
  shell: >
           {{ etcd_install_prefix }}/etcd/build 
           chdir="{{ etcd_install_prefix }}/etcd"
  sudo: yes
  when: etcd_installed.stat.exists != true

- name: mark as installed
  file: path={{ etcd_install_prefix }}/etcd/installed.ok mode=0644 state=touch
  sudo: yes

- name: setup etcd in /etc/init
  template: src=upstart_etcd.j2 dest=/etc/init/etcd.conf mode=0644
  notify:
    - reload etcd
  sudo: yes

- name: ensure etcd is started
  service: name=etcd state=started
  sudo: yes
