- name: Updates apt cache
  apt: update_cache=true
  sudo: yes

- name: Installs git and goloang
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - golang
  sudo: yes

- name: check whether already installed
  stat: path={{ install_prefix }}/etcd/installed.ok
  register: etcd_installed

- name: checkout code
  git: repo=https://github.com/coreos/etcd.git
       dest={{ install_prefix }}/etcd
       version=v0.4.1
  sudo: yes
  when: etcd_installed.stat.exists != true

- name: build etcd
  shell: >
           {{ install_prefix }}/etcd/build 
           chdir="{{ install_prefix }}/etcd"
  sudo: yes
  when: etcd_installed.stat.exists != true

- name: mark as installed
  file: path={{ install_prefix }}/etcd/installed.ok mode=0644 state=touch
  sudo: yes

